service: mobilepayments # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs8.10

  # you can overwrite defaults here
  stage: dev
  region: us-east-1

functions:
  app:
    handler: lambda.handler
    events: # events trigger lambda functions
      - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors: true
